path: D:\shixun\sss\Train
train: images\train
val: images\val

batch: 8

# Classes
names:
  0 : plate
  1 : 0
  2 : 1
  3 : 2
  4 : 3
  5 : 4
  6 : 5
  7:  6
  8 : 7
  9 : 8
  10 : 9
  11 : A
  12 : B
  13 : C
  14 : D
  15 : E
  16 : F
  17 : G
  18 : H
  19 : J
  20 : K
  21 : L
  22 : M
  23 : N
  24 : P
  25 : Q
  26 : R
  27 : S
  28 : T
  29 : U
  30 : V
  31 : W
  32 : X
  33 : Y
  34 : Z
  35 : 澳
  36 : 川
  37 : 鄂
  38 : 甘
  39 : 赣
  40 : 港
  41 : 贵
  42 : 桂
  43 : 黑
  44 : 沪
  45 : 吉
  46 : 冀
  47 : 津
  48 : 晋
  49 : 京
  50 : 警
  51 : 辽
  52 : 鲁
  53 : 蒙
  54 : 闽
  55 : 宁
  56 : 青
  57 : 琼
  58 : 陕
  59 : 苏
  60 : 皖
  61 : 湘
  62 : 新
  63 : 学
  64 : 渝
  65 : 豫
  66 : 粤
  67 : 云
  68 : 浙
  69 : 藏